export const MEME_CAPTIONS: string[] = [
  'Totally safe. Trust me bro.',
  'This one cured my doomscrolling (not really).',
  'If you skip this, you hate fun.',
  'Looks harmless. That\'s how they get you.',
  '99% safe. 1% character development.',
  'The algorithm picked this JUST for you.',
  'It\'s giving… definitely safe vibes.',
  'One more swipe won\'t hurt. Right?',
  'This meme is medically approved (by me).',
  'Skip if you fear happiness.',
  'Warning: may contain consequences.',
  'Cute content… or a trap. Place your bet.',
  'Your future self says: don\'t click. Or do.',
  'If this is a bomb, it\'s your fault now.',
  'Satisfaction guaranteed (legally not).',
  'This is fine 🔥 (it\'s not).',
  'High risk, high dopamine.',
  'Agent-free zone (allegedly).',
  'Open it. What\'s the worst that could happen?',
  'Congratulations! You found… uncertainty.',
];
