export const SAFE_ICON_FALLBACK = '\u{1F6E1}\uFE0F';

export interface SafeCardConfig {
  id: string;
  title: string;
  subtitle: string;
  icon: string;
}

export const SAFE_CARDS_CONFIG: readonly SafeCardConfig[] = [
  { id: 'strawberry_dancing',   title: 'Strawberry Dancing',        subtitle: 'She moves, she grooves',                   icon: '\u{1F353}' },
  { id: 'butterfly_flying',     title: 'Butterfly Flying',          subtitle: 'Majestic and unbothered',                  icon: '\u{1F98B}' },
  { id: 'taxi_7788',            title: 'Taxi 7788',                 subtitle: 'Meter has been running since 2019',         icon: '\u{1F695}' },
  { id: 'fruit_circle',         title: 'Fruit Circle',              subtitle: 'Watermelon disco energy',                  icon: '\u{1F349}' },
  { id: 'cat_reviews_water',    title: 'Cat Reviews Water',         subtitle: '3 out of 10, too wet',                     icon: '\u{1F431}' },
  { id: 'grandma_filters',      title: 'Grandma Discovers Filters', subtitle: 'She is beauty, she is grace',              icon: '\u{1F475}' },
  { id: 'dog_sunglasses',       title: 'Dog With Sunglasses',       subtitle: 'Cooler than you will ever be',             icon: '\u{1F436}' },
  { id: 'frog_dj',              title: 'Frog DJ Set',               subtitle: 'Ribbiting beats only',                     icon: '\u{1F438}' },
  { id: 'man_explains',         title: 'Man Explains Everything',   subtitle: 'Nobody asked, but here he goes',           icon: '\u{1F937}\u200D\u2642\uFE0F' },
  { id: 'slime_cut',            title: 'Satisfying Slime Cut',      subtitle: 'Your brain needed this',                   icon: '\u{1FAE7}' },
  { id: 'weather_forecast',     title: 'Chaotic Weather Report',    subtitle: 'Tornado or sunshine? Yes.',                icon: '\u{1F32A}\uFE0F' },
  { id: 'motivational_potato',  title: 'Motivational Potato',       subtitle: 'Believe in yourself, spud',                icon: '\u{1F954}' },
  { id: 'invisible_prank',      title: 'Invisible Prank',           subtitle: 'You cannot see me (but your trust issues can)', icon: '\u{1FAE5}' },
  { id: 'support_duck',         title: 'Emotional Support Duck',    subtitle: 'Quack through the pain',                   icon: '\u{1F986}' },
  { id: 'perfect_pancake',      title: 'The Perfect Pancake',       subtitle: 'Flipped once. Flawless.',                  icon: '\u{1F95E}' },
  { id: 'diy_glue',             title: 'DIY Gone Wrong',            subtitle: 'Glue is not the answer (or is it)',        icon: '\u{1F9F4}' },
  { id: 'ai_celebrity',         title: 'AI-Generated Celebrity',    subtitle: 'Almost real. Almost.',                     icon: '\u{1F916}' },
  { id: 'overacting_actor',     title: 'Overacting Actor',          subtitle: 'Oscar? No. Effort? Maximum.',              icon: '\u{1F3AD}' },
  { id: 'man_runs',             title: 'Man Runs From Nothing',     subtitle: 'Full sprint, zero context',                icon: '\u{1F3C3}' },
  { id: 'cat_yoga',             title: 'Cat Doing Yoga',            subtitle: 'Downward dog but make it feline',          icon: '\u{1F408}' },
  { id: 'tech_bro',             title: 'Tech Bro Explains',         subtitle: 'Not a scam, a paradigm shift',             icon: '\u{1F9D1}\u200D\u{1F4BB}' },
  { id: 'barista',              title: 'Barista on 3 Espressos',    subtitle: 'Vibrating at a molecular level',           icon: '\u2615' },
  { id: 'fruit_sunglasses',     title: 'Pineapple With Shades',     subtitle: 'Living its best tropical life',            icon: '\u{1F34D}' },
  { id: 'fake_lifehack',        title: 'Fake Life Hack',            subtitle: 'Step 1: lie. Step 2: profit.',             icon: '\u{1F9EA}' },
  { id: 'slow_motion_jump',     title: 'Slow Motion Jump',          subtitle: 'Peak athleticism (debatable)',             icon: '\u{1F998}' },
  { id: 'makeup_reveal',        title: 'Makeup Reveal',             subtitle: 'Wait for it... wait for it...',            icon: '\u{1F484}' },
  { id: 'sad_hamster',          title: 'Sad Hamster',               subtitle: 'Going through a lot right now',            icon: '\u{1F439}' },
  { id: 'dancing_broccoli',     title: 'Dancing Broccoli',          subtitle: 'Vegetables have more fun',                 icon: '\u{1F966}' },
  { id: 'fish_music',           title: 'Fish Vibing to Music',      subtitle: 'Glub glub glub (the beat drops)',          icon: '\u{1F41F}' },
  { id: 'crypto_guy',           title: 'Crypto Guy',                subtitle: 'Still holding. Still explaining.',         icon: '\u{1FA99}' },
  { id: 'edited_sunset',        title: 'Over-Edited Sunset',        subtitle: 'Saturation: yes. All of it.',              icon: '\u{1F305}' },
  { id: 'clumsy_ninja',         title: 'Clumsy Ninja',              subtitle: 'Stealth: 0. Entertainment: 100.',          icon: '\u{1F977}' },
  { id: 'grocery_list',         title: 'Dramatic Grocery List',     subtitle: 'The eggs are non-negotiable',              icon: '\u{1F6D2}' },
  { id: 'cat_knocks',           title: 'Cat Knocks Things Off',     subtitle: 'Physics experiment in progress',           icon: '\u{1F95B}' },
  { id: 'fake_interview',       title: 'Fake Street Interview',     subtitle: 'Totally not scripted (it is)',             icon: '\u{1F3A4}' },
  { id: 'whisper_challenge',    title: 'Whisper Challenge',         subtitle: 'What did you say? WHAT?!',                 icon: '\u{1F92B}' },
  { id: 'microwave_cooking',    title: 'Microwave Cooking',         subtitle: 'Radiation edition of fine dining',         icon: '\u{1F372}' },
  { id: 'influencer_apology',   title: 'Influencer Apology',        subtitle: 'Sorry you feel that way',                  icon: '\u{1F4DD}' },
  { id: 'dog_hat',              title: 'Dog Wearing a Hat',         subtitle: 'Fashion icon. No notes.',                  icon: '\u{1F3A9}' },
  { id: 'slow_clap',            title: 'Slow Clap',                subtitle: 'Sarcasm loading... 47%',                    icon: '\u{1F44F}' },
  { id: 'intense_workout',      title: 'Intense Workout',          subtitle: 'Pain is just weakness crying',              icon: '\u{1F3CB}\uFE0F' },
  { id: 'frog_mic',             title: 'Frog With Microphone',      subtitle: 'One croak wonder',                         icon: '\u{1F399}\uFE0F' },
  { id: 'cat_judges',           title: 'Cat Judging You',           subtitle: 'You have been found wanting',              icon: '\u{1F440}' },
  { id: 'fake_magic',           title: 'Fake Magic Trick',          subtitle: 'The trick is there is no trick',           icon: '\u{1FA84}' },
  { id: 'emotional_bread',      title: 'Emotional Bread',           subtitle: 'This loaf has feelings',                   icon: '\u{1F35E}' },
  { id: 'man_dances',           title: 'Man Dances Alone',          subtitle: 'Main character energy, zero audience',     icon: '\u{1F57A}' },
  { id: 'gym_quote',            title: 'Gym Quote Over Sunset',     subtitle: 'Grind never stops (except weekends)',      icon: '\u{1F4E3}' },
  { id: 'baby_laugh',           title: 'Baby Laughing',             subtitle: 'Peak comedy, zero words',                  icon: '\u{1F476}' },
  { id: 'robot_fail',           title: 'Robot Fail Compilation',    subtitle: 'The singularity can wait',                 icon: '\u{1F916}' },
  { id: 'coffee_pour',          title: 'Satisfying Coffee Pour',    subtitle: 'ASMR for the chronically online',          icon: '\u2615' },
  { id: 'plot_twist',           title: 'Plot Twist',                subtitle: 'It was the friend all along',              icon: '\u{1F300}' },
  { id: 'fake_news',            title: 'Fake Breaking News',        subtitle: 'Sources: trust me bro',                    icon: '\u{1F4F0}' },
  { id: 'door_open',            title: 'Door Opens Dramatically',   subtitle: 'Behind it? Disappointment.',               icon: '\u{1F6AA}' },
  { id: 'cat_attitude',         title: 'Cat With Attitude',         subtitle: 'Crown earned, not given',                  icon: '\u{1F451}' },
  { id: 'bubble_wrap',          title: 'Bubble Wrap ASMR',          subtitle: 'Pop pop pop (serotonin restored)',         icon: '\u{1FAE7}' },
  { id: 'tourist',              title: 'Lost Tourist',              subtitle: 'Holding map upside down since 2009',       icon: '\u{1F9F3}' },
  { id: 'skateboard_fail',      title: 'Skateboard Fail',           subtitle: 'Gravity: 1, Skater: 0',                   icon: '\u{1F6F9}' },
  { id: 'makeup_wrong',         title: 'Makeup Gone Wrong',         subtitle: 'Bold choices were made',                   icon: '\u{1F635}' },
  { id: 'parrot',               title: 'Parrot Repeating Secrets',  subtitle: 'Polly wants your privacy',                 icon: '\u{1F99C}' },
  { id: 'banana_phone',         title: 'Banana Phone',              subtitle: 'Ring ring ring ring...',                   icon: '\u{1F34C}' },
  { id: 'confused_math',        title: 'Confused Math Lady',        subtitle: 'Numbers are not adding up',                icon: '\u{1F9EE}' },
  { id: 'office_dance',         title: 'Office Dance Break',        subtitle: 'HR has been notified',                     icon: '\u{1F4BC}' },
  { id: 'suspicious_sandwich',  title: 'Suspicious Sandwich',       subtitle: 'It knows what you did',                    icon: '\u{1F96A}' },
  { id: 'rain_scene',           title: 'Dramatic Rain Scene',       subtitle: 'Staring into the distance required',       icon: '\u{1F327}\uFE0F' },
  { id: 'horror_cat',           title: 'Horror Movie Cat',          subtitle: 'Jump scare but fluffy',                    icon: '\u{1F631}' },
  { id: 'puppy_nap',            title: 'Puppy Napping',             subtitle: 'Do not disturb (or else)',                 icon: '\u{1F4A4}' },
  { id: 'glitch_selfie',        title: 'Glitched Selfie',           subtitle: 'Art or accident? You decide.',             icon: '\u{1F4F1}' },
  { id: 'dramatic_sip',         title: 'Dramatic Tea Sip',          subtitle: 'None of my business though',               icon: '\u{1FAD6}' },
  { id: 'life_coach',           title: 'Self-Proclaimed Life Coach', subtitle: 'Advice from someone who burns toast',     icon: '\u{1F9D8}' },
  { id: 'motivational_rock',    title: 'Motivational Rock',         subtitle: 'You rock. Literally.',                     icon: '\u{1FAA8}' },
  { id: 'cat_cucumber',         title: 'Cat vs Cucumber',           subtitle: 'Trust: destroyed',                         icon: '\u{1F952}' },
  { id: 'desk_setup',           title: 'Desk Setup Tour',           subtitle: 'RGB everything. Productivity: zero.',      icon: '\u{1F5A5}\uFE0F' },
  { id: 'eyebrow_raise',        title: 'The Eyebrow Raise',         subtitle: 'Judgment delivered silently',              icon: '\u{1F928}' },
  { id: 'viral_challenge',      title: 'Viral Challenge',           subtitle: 'Do not try this at home (they did)',       icon: '\u{1F4F1}' },
  { id: 'slow_blink',           title: 'Slow Blink',                subtitle: 'Maximum disrespect, minimum effort',      icon: '\u{1F60C}' },
  { id: 'shiny_sneakers',       title: 'Shiny New Sneakers',        subtitle: 'Flexed once, regretted never',             icon: '\u{1F45F}' },
  { id: 'ice_drop',             title: 'Ice Cube Drop',             subtitle: 'Plop. Content achieved.',                  icon: '\u{1F9CA}' },
  { id: 'turtle_race',          title: 'Turtle Race',               subtitle: 'Speed is relative (very relative)',        icon: '\u{1F422}' },
  { id: 'deep_quote',           title: 'Deep Quote',                subtitle: 'Posted unironically at 2 AM',              icon: '\u{1F9E0}' },
  { id: 'coffee_fail',          title: 'Coffee Spill',              subtitle: 'Monday energy in liquid form',             icon: '\u274C' },
  { id: 'fan_whisper',          title: 'Fan Whisper ASMR',          subtitle: 'Shhh... the fan is speaking',              icon: '\u{1FAAD}' },
  { id: 'edited_sky',           title: 'Over-Edited Night Sky',     subtitle: 'The Milky Way does not look like that',    icon: '\u{1F30C}' },
  { id: 'banana_slip',          title: 'Banana Slip',               subtitle: 'Classic comedy, zero innovation',          icon: '\u{1F34C}' },
  { id: 'serious_cat',          title: 'Serious Business Cat',      subtitle: 'Your quarterly report is late',            icon: '\u{1F4BC}' },
  { id: 'motivational_alarm',   title: 'Motivational Alarm Clock',  subtitle: 'Rise and grind (or just snooze)',          icon: '\u23F0' },
  { id: 'dog_mirror',           title: 'Dog Discovers Mirror',      subtitle: 'Who is that handsome boy? Me?!',           icon: '\u{1FA9E}' },
  { id: 'frog_meditation',      title: 'Frog Meditating',           subtitle: 'Inner peace, outer swamp',                 icon: '\u{1F438}' },
  { id: 'man_plant',            title: 'Man Talks to Plant',        subtitle: 'The plant thrives. The man does not.',     icon: '\u{1FAB4}' },
  { id: 'fitness_hack',         title: 'Fake Fitness Hack',         subtitle: 'Abs in 3 minutes (spoiler: no)',           icon: '\u{1F9EA}' },
  { id: 'dramatic_typing',      title: 'Dramatic Typing',           subtitle: 'Writing an email like a manifesto',        icon: '\u2328\uFE0F' },
  { id: 'squirrel_snack',       title: 'Squirrel Snack Time',       subtitle: 'Aggressive munching, zero shame',          icon: '\u{1F43F}\uFE0F' },
  { id: 'overhyped_trailer',    title: 'Overhyped Trailer',         subtitle: 'Coming soon (to disappoint you)',          icon: '\u{1F39E}\uFE0F' },
  { id: 'traffic_cone',         title: 'Traffic Cone Dancing',      subtitle: 'Found its calling at 3 AM',                icon: '\u{1F6A7}' },
  { id: 'fake_psychic',         title: 'Fake Psychic',              subtitle: 'I see... money leaving your wallet',       icon: '\u{1F52E}' },
  { id: 'sad_violin',           title: 'Sad Violin',                subtitle: 'The smallest one, playing just for you',   icon: '\u{1F3BB}' },
  { id: 'glitter_explosion',    title: 'Glitter Explosion',         subtitle: 'You will be finding this for months',      icon: '\u2728' },
  { id: 'complicated_recipe',   title: 'Complicated Recipe',        subtitle: '47 steps for toast',                       icon: '\u{1F9D1}\u200D\u{1F373}' },
  { id: 'hair_flip',            title: 'Dramatic Hair Flip',        subtitle: 'Main character energy: activated',         icon: '\u{1F487}\u200D\u2640\uFE0F' },
  { id: 'cat_box',              title: 'Cat in a Box',              subtitle: 'If it fits, it sits',                      icon: '\u{1F4E6}' },
  { id: 'calm_ocean',           title: 'Calm Ocean Sounds',         subtitle: 'Finally, some peace (just kidding)',        icon: '\u{1F30A}' },
];

export function getSafeCardIcon(card: SafeCardConfig): string {
  return card.icon || SAFE_ICON_FALLBACK;
}
